# Generated by Django 5.2.13 on 2026-04-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_created_at_user_email_verification_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
