# Generated by Django 5.2.13 on 2026-04-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="label",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
