# Generated by Django 5.2.13 on 2026-05-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
        ("notes", "0002_alter_note_options_note_color_note_is_pinned_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="label",
        ),
        migrations.AddField(
            model_name="note",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="notes", to="labels.label"
            ),
        ),
    ]
