# Generated by Django 5.2.13 on 2026-05-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_remove_note_label_note_labels"),
        ("users", "0003_user_otp_code_user_otp_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, related_name="shared_notes", to="users.user"
            ),
        ),
    ]
