# Generated by Django 5.2.13 on 2026-05-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_note_collaborator_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
