# Generated by Django 5.2.13 on 2026-05-18 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_note_deleted_at_note_is_deleted"),
        ("users", "0003_user_otp_code_user_otp_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteCollaboratorInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[("view", "Can view"), ("edit", "Can edit")],
                        default="view",
                        max_length=10,
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_note_collaborator_invites",
                        to="users.user",
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_collaborator_invites",
                        to="users.user",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborator_invites",
                        to="notes.note",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("note", "invited_user")},
            },
        ),
    ]
